defaults:
  - override hydra/job_logging: default

device: ["cuda"]
num_epochs: [10]
lr_decay_epoch: [7] # 0.1 decay

feature_pass: ['triangle', 'persistence']


use_bn: [True, False]

batch_sizes: [1024]
learning_rates: [0.01, 0.05, 0.001, 0.0001]

prob_of_using_new_values: [1.0, 0.75, 0.5, 0.25]

num_layers: [2, 3, 4, 5, 6, 7]

l2_lambda: [0]
seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# dataset
# cifar10 [3072, 10]
# mnist, fashion_mnist [784, 10]

dataset_name: ['cifar10']
data_dims: [[3072, 10]]

wandb_project: "NewWvsOldW"
results_dir: '/home/al/projects/experimental/multulayer/results'